
*** Variables ***
${CLIENT_SITE_URL}          https://my-dev.d.com
${CLIENT_SITE_CMS_URL}          https://my-cms-dev.d.com
${PUBLIC_SITE_URL}          https://www-dev.d.com
${PUBLIC_SITE_CMS_URL}          https://www-cms-dev.d.com
${OKTA_URL}      https://okta-dev.d.com
${OKTA_AUTH_SERVER}     /oauth2/ausxrs1osr3WJVxfq0h7/v1/token
@{OKTA_CLIENTID_CLIENTSEC}        0oa12bpcyxm7w8UT20h8        0fkN-FkpG62CtAaGJGQHAWhAEKLg9qG61xI8ADfX
${CRM_API_URL}    https://crmapi-dev.d.com
${CAREERS_URL}              https://careers-dev.d.com
${XLINK_MARKETNOMEMORY_URL}         https://my-cms-dev.d.com/xlink/DtNzyuEM2J39nDJ3rlwhWbGCINI01P5o9kF98FC1ddQ4X5VY0ah_nRdrXnc-9feC8qcxXLJxgDh2MozAHxzVbi1nghkHvQqnfsZu1Aow1NjPAqBhVSPL8gbF2GgaVtMrbOGYQcR_4BnaGSRaFIx9JcB_soMRz5nZ7ddIzNJ4A2E1