
*** Variables ***
${CLIENT_SITE_URL}          https://my-preview5.d.com
${CLIENT_SITE_CMS_URL}          https://my-cms-preview5.d.com
${PUBLIC_SITE_URL}          https://www-preview5.d.com
${PUBLIC_SITE_CMS_URL}          https://www-cms-preview5.d.com
${OKTA_URL}      https://okta-dev.d.com
${OKTA_AUTH_SERVER}     /oauth2/ausxrs1osr3WJVxfq0h7/v1/token
@{OKTA_CLIENTID_CLIENTSEC}        0oa12bpcyxm7w8UT20h8        0fkN-FkpG62CtAaGJGQHAWhAEKLg9qG61xI8ADfX
${CRM_API_URL}    https://crmapi-dev.d.com
${CAREERS_URL}              https://careers-preview5.d.com
${XLINK_MARKETNOMEMORY_URL}         https://my-preview5.d.com/xlink/1j16tbCxkb-nkEgiw0_YR6qgeb0RgzolSM6c2TplOZVwKIMKkzWi8sICdqIbuxFPQwxn-PNMmo83xUZSWufT5k9Ykz3VBHSpI9ug3VurW_yfYAc9H39R6A6Gx5QXOn0ZeonrcY3l6f9cYMY-3OjHBIoNCqxWEklveRCptHNsSFU1