*** Variables ***
${CLIENT_SITE_URL}                         https://my.d.com
${CLIENT_SITE_CMS_URL}                     https://my-cms.d.com
${PUBLIC_SITE_URL}                         https://www.d.com
${PUBLIC_SITE_CMS_URL}                     https://www-cms.d.com
${QLIK_URL}                                http://astdc-qview01p/qlikview/index.htm
${CVENT_URL}                               https://cventapi.d.com
${CRM_API_URL}                             https://crmapi.d.com
${BROWSER}                                 Firefox
${CAREERS_URL}                             https://careers.d.com
${PEOPLE_URL}                              http://people.d.com
${SCREENS_URL}                             http://screens.d.com
${HISTORY_URL}                             http://history.d.com
${INVESTOR_REPORTING_URL}                  http://investorreporting.d.com
${GIPS_URL}                                http://gips.d.com/VehicleChangeReview
${CARS_URL}                                http://cars.d.com
${PLATINUM_REPORTING_URL}                  http://platinumreporting.d.com
${PLATINUM_REPORTING_REPORTFILESERVER}     //bursrv-pv003/dfa/TECHNOLOGY/PlatinumReporting/Prd
${OKTA_URL}                                https://okta.d.com
${OKTA_AUTH_SERVER}                        /oauth2/aus8dcc18ts4DbZCa357/v1/token
@{OKTA_CLIENTID_CLIENTSEC}                 0oagch4moy65dqDAp357        RWH1yM6irrAhs1OdReOQOsqqqWy6YxHG6RFCbUe-
${XLINK_MARKETNOMEMORY_URL}                https://my-cms.d.com/xlink/IWACiQw7haAIK-eG1EdJKK84zTqTKTVZa7VFgAh0ep6-_5WqvM9weOTYeAh5aZt6jeM5rk7vYxAjZe9LAl-UBBbtznNQs1833NGe8I4DC15TknxKPriWv9ighizC1xJ0T6S-pihwSnQ-lpxRFppXoVy1VRth9jUDWOSC0yiPXK41
${FMS_URL}                                 https://fms.d.com/
${HA_SITE_URL}                             https://info.d.com/
${HA_SITE_URL2}                            https://info2.d.com/
${JENKINS_URL}                             https://smt-jenkins.d.com