
*** Variables ***
${CLIENT_SITE_URL}          https://my-stage.d.com
${CLIENT_SITE_CMS_URL}          https://my-cms-stage.d.com
${PUBLIC_SITE_URL}          https://www-stage.d.com
${PUBLIC_SITE_CMS_URL}          https://www-cms-stage.d.com
# Stage UI is hooked in backend to prod(Blue/Green)
${OKTA_URL}      https://okta.d.com
${OKTA_AUTH_SERVER}     /oauth2/aus8dcc18ts4DbZCa357/v1/token
@{OKTA_CLIENTID_CLIENTSEC}        0oagch4moy65dqDAp357        RWH1yM6irrAhs1OdReOQOsqqqWy6YxHG6RFCbUe-
${CRM_API_URL}              https://crmapi.d.com
${CAREERS_URL}              https://careers-stage.d.com
${XLINK_MARKETNOMEMORY_URL}         https://my-cms-stage.d.com/xlink/4QuIo6GSjAmau1uU1U-mj9ASu661S-nYIq9m3aQze41-kuLncNCTkH0FCwVs7bS14vHRweLV1HokBCKcMH4_0st0DXwM3L0Syd7UkYsEGCefKORN3j9FJYtln1wsZuQsCE4p424mGvgDhVkurydoSCfI1kbdJt68CkhN14ojfN41
