
*** Variables ***
${CLIENT_SITE_URL}          https://my-uat.d.com
${CLIENT_SITE_CMS_URL}          https://my-cms-uat.d.com
${PUBLIC_SITE_URL}          https://www-uat.d.com
${PUBLIC_SITE_CMS_URL}          https://www-cms-uat.d.com
# UAT UI is hooked in backend to stage
${OKTA_URL}      https://okta-stg.d.com
${OKTA_AUTH_SERVER}     /oauth2/ausxsair7gmXrDCbV0h7/v1/token
@{OKTA_CLIENTID_CLIENTSEC}        0oa12bvcnu3UsFYGs0h8        h1siErOytEtaX3HncbdYBmzM3Pe1kDUO1cINmBCQ
${CRM_API_URL}              https://crmapi-stage.d.com
${CAREERS_URL}              https://careers-uat.d.com
${XLINK_MARKETNOMEMORY_URL}          https://my-cms-uat.d.com/xlink/YQ2W7Mp-5Avyd1vzeaGjSq5woqOleM3T73_a-I1Iqjp2Et_qIao0MnsBGw9XEeFri6z1pftipBOgO0mzJK29aDPj2evNpoSQTKwwwz4FqWDdi5Uc-pdnCeRaVG4XejCZNFKe6VDgdO6xpZ0Af8XhXqYGKhzVR5t1oeuUubRTBBE1