/*
DO NOT EDIT THIS FILE VIA NEW RELIC.
This file is under version control in ddx_models repo:
https://github.com/d-Tech/smt-ddx-client-site/blob/main/new_relic_synthetic_monitors/ClientSite-Browse+Search.js

Script is put into place in 'Client Site | Browse and Search' monitor:
https://one.newrelic.com/nr1-core/synthetics/monitor-settings/MzQ2NDI1fFNZTlRIfE1PTklUT1J8OTNlNTAyNDgtMTA5Zi00ZWIyLTk4OGMtZmYyNWYzMmM5ZmRh
*/

$browser.manage().window().setSize(1600,1200);

var username = "dddx+external.newrelictest@gmail.com";
var password = $secure.CLIENTSITE_EXTERNAL_NEWRELIC;
const countries = [ 'Australia','United Kingdom', 'Germany','Canada','United States'];

var assert = require('assert');

$util.insights.set('script_start', Math.round(+new Date()));

// Set custom user agent to bypass financial professional affirmation modal.
$browser.addHeader('User-Agent', 'dfa_newrelic-synthetic');

(async function main() {
  // Go to login page.
  await $browser.get("https://my.d.com/login");

  // Wait for login form to appear.
  await $browser.waitForAndFindElement($driver.By.xpath("//button[@type='submit' and text()='LOG IN']"), 30000);

  // Enter username.
  await $browser.findElement($driver.By.name("email")).sendKeys(username);

  // Enter password.
  await $browser.findElement($driver.By.name("password")).sendKeys(password);

  // Click/submit login form.
  await $browser.findElement($driver.By.xpath("//button[@type='submit' and text()='LOG IN']")).click();


  // Sequentially change UX country for each country in the list
  for (let i = 0; i < countries.length; i++) {
    let country = countries[i];
    if (country) {

    console.log("Using country- ", country);
    await changeUXCountry(country);
    // Check presence of search box after country change
    console.log("Looking for client-search-input");
    await $browser.waitForAndFindElement($driver.By.css('[data-qa="client-search-input"]'), 10000);

    // Check the first browse card
    console.log("Checking for a browse card");
    await $browser.wait($driver.until.elementsLocated($driver.By.className('coveo-headless-card-layout')), 10000);

    }

  }
})().catch(function(err) {
  $browser.takeScreenshot();
  //console.error(`Script failed for ${countries[i]}`, err);
  throw err;
});

async function changeUXCountry(country) {
  console.log("Changing UX country to:", country);

  // Click the profile expand link
  console.log("Waiting for profile link");
  await $browser.waitForAndFindElement($driver.By.css('[data-qa="header-profile-link"]'), 20000)
    .then(el => el.click());

  // Click the profile preferences link
  console.log("Waiting for preferences - clicking on preferences link");
  await $browser.waitForAndFindElement($driver.By.css('[data-qa="header-profile-preferences"]'), 10000)
    .then(el => el.click());

  // Click the Preferences tab
  console.log("Waiting for preferences");
  await $browser.waitForAndFindElement($driver.By.id('preferences'), 10000)
    .then(el => el.click());

  // Click the "Change" link in preferences
  console.log("Preferences page: Clicking on change country");
  await $browser.waitForAndFindElement($driver.By.xpath('//*[contains(@class,"profile-preference-content-preferences-title")]//*[text()="Change"]'),
    10000).then(el => el.click());

  // Click the country dropdown
  console.log("Preferences page: Selecting country");
  await $browser.waitForAndFindElement($driver.By.css('.dfa-dropdown-init-label'),10000).then(el => el.click());

  // Select the desired country by its aria-label
  console.log("Preferences page: Changing Country");
  await $browser.waitForAndFindElement($driver.By.css(`[aria-label="${country}"]`), 10000).then(el => el.click());

  // Click the "ACCEPT" button
  console.log("Preferences page: Accepting");
  await $browser.waitForAndFindElement($driver.By.css('[aria-label="ACCEPT"]'), 10000).then(el => el.click());

  console.log("Preferences page: Click on back to profile");
  await $browser.waitForAndFindElement($driver.By.css('[aria-label="BACK TO PROFILE"]'), 20000).then(el => el.click());

  console.log("Preferences page: Click on back to home page");
  await $browser.waitForAndFindElement($driver.By.css('[data-qa="home-page-image-logo"]'), 10000).then(el => el.click());
}