/*
DO NOT EDIT THIS FILE VIA NEW RELIC.
This file is under version control in ddx-client-site repo(DDXP-5436):
https://stash.d.com/projects/QA/repos/ddx-client-site/browse/new_relic_synthetic_monitors/OneTrust-GDPR.js

Script is put into place in 'OneTrust-GDPR' monitor:
https://one.newrelic.com/nr1-core/synthetics-nerdlets/monitor-settings/MzQ2NDI1fFNZTlRIfE1PTklUT1J8MzFlN2Q5N2YtODA5Yi00ZTBmLTlmNzgtNjEzN2M2Y2I4YjMz?account=346425&duration=1800000&state=a8b13d77-aab5-d947-dc12-92ec0ddb5355
*/

var assert = require('assert');
const site = 'https://www.d.com';
const onetrust_cookie = 'OptanonConsent';
const onetrust_modal_button = 'onetrust-pc-btn-handler'

$webDriver.get(site).then(function(){

  return $webDriver.sleep(5000).then(function(){

  return $webDriver.manage().getCookie(onetrust_cookie).then(function(cookie){
    console.log(cookie);
    var categories_array = cookie.value.match(/(?<=&groups=).[^&]*/).toString().split("%2C");
                /*
CustomGroupId       GroupName                           Status
1                   Strictly Necessary Cookies          Always Active
2                   Performance Cookies                 Inactive
4                   Targeting Cookies                   Inactive
             */
    return categories_array.forEach((category) => {
                                                             var [k,v] = category.split("%3A");
                                                             switch(k) {
                                                                        case '1':
                                                                               assert.equal(v,1,"Unexpected value for category "+k);
                                                                               break;
                                                                         case '2':
                                                                                assert.equal(v,0,"Unexpected value for category "+k);
                                                                                break;
                                                                         case '4':
                                                                                assert.equal(v,0,"Unexpected value for category "+k);
                                                                         }

                                                  });
    }).then (function(){
    return $webDriver.findElement($selenium.By.id(onetrust_modal_button)).then(function(element){
         return element.getText().then(function(text){
                assert(text, 'Button text on OneTrust modal is empty or undefined');
    });
  });
    });
  });
})
