/*
DO NOT EDIT THIS FILE VIA NEW RELIC.
This file is under version control in ddx_models repo(DDXP-5436):
https://stash.d.com/projects/QA/repos/ddx-client-site/browse/new_relic_synthetic_monitors/OneTrust-CCPA.js

Script is put into place in 'OneTrust-CCPA' monitor:
https://one.newrelic.com/nr1-core/synthetics-nerdlets/monitor-settings/MzQ2NDI1fFNZTlRIfE1PTklUT1J8MjBmMWRmMmItYTU2ZC00MTI2LWE3MjEtY2NmZjUyMDg4MTM2?account=346425&duration=1800000&state=56c72bea-0744-e62a-2bed-c92a9e73a319
*/

var assert = require('assert');
const site = 'https://www.d.com';
const onetrust_cookie = 'OptanonConsent';
const onetrust_modal_button = 'onetrust-pc-btn-handler'
const useragent = 'dimobot';

//Customize user agent
$headers.add('User-Agent', useragent);

$webDriver.get(site).then(function(){

  return $webDriver.sleep(5000).then(function(){

  $webDriver.manage().getCookie(onetrust_cookie).then(function(cookie){
    console.log(cookie);
    var categories_array = cookie.value.match(/(?<=&groups=).[^&]*/).toString().split("%2C");
                   /*
CustomGroupId       GroupName                           Status
1                   Strictly Necessary Cookies          Always Active
SPD_BG              Sale of Personal Data               Active
2                   Performance Cookies                 Active
4                   Targeting Cookies                   Active
             */

    return categories_array.forEach((category) => {
                                                             var [k,v] = category.split("%3A");
                                                             switch(k) {
                                                                        case '1':
                                                                               assert.equal(v,1,"Unexpected value for category "+k);
                                                                               break;
                                                                         case 'SPD_BG':
                                                                                assert.equal(v,1,"Unexpected value for category "+k);
                                                                                break;
                                                                         case '2':
                                                                                assert.equal(v,1,"Unexpected value for category "+k);
                                                                                break;
                                                                         case '4':
                                                                                assert.equal(v,1,"Unexpected value for category "+k);
                                                                         }

                                                  });
    }).then (function(){
    return $webDriver.findElement($selenium.By.id(onetrust_modal_button)).then(function(element){
    return element.getText().then(function(text){
      assert(text, 'Button text on OneTrust modal is empty');
                                                });
                                                                                                });
                     });
});
})
