/*
DO NOT EDIT THIS FILE VIA NEW RELIC.
This file is under version control in ddx-client-site repo(DDXP-5436):
https://stash.d.com/projects/QA/repos/ddx-client-site/browse/new_relic_synthetic_monitors/OneTrust-GLOBAL.js

Script is put into place in 'OneTrust-GLOBAL' monitor:
https://one.newrelic.com/nr1-core/synthetics-nerdlets/monitor-settings/MzQ2NDI1fFNZTlRIfE1PTklUT1J8NmNhMTExOGItMzI4OS00NjRmLWExNjUtODVhZGE1ZmY5ZGE0?account=346425&duration=1800000&state=3091e1be-837c-2895-7f0c-583798655995
*/

var assert = require('assert');
const site = 'https://www.d.com';
const onetrust_cookie = 'OptanonConsent';
const useragent = 'dimobot';

//Customize user agent
$headers.add('User-Agent', useragent);

$webDriver.get(site).then(function(){

  return $webDriver.sleep(5000).then(function(){
    $webDriver.manage().getCookies().then(function(cookies){
    console.log(cookies);
    })
    return $webDriver.manage().getCookie(onetrust_cookie).then(function(cookie){
            var categories_array = cookie.value.match(/(?<=&groups=).[^&]*/).toString().split("%2C");
            /*
CustomGroupId       GroupName                           Status
1                   Strictly Necessary Cookies          Always Active
2                   Performance Cookies                 Active
4                   Targeting Cookies                   Inactive
             */
             return categories_array.forEach((category) => {
                                                             var [k,v] = category.split("%3A");
                                                             switch(k) {
                                                                        case '1':
                                                                               assert.equal(v,1,"Unexpected value for category "+k);
                                                                               break;
                                                                         case '2':
                                                                                assert.equal(v,1,"Unexpected value for category "+k);
                                                                                break;
                                                                         case '4':
                                                                                assert.equal(v,0,"Unexpected value for category "+k);
                                                                         }
                                                         });
                                             });
});
})
